# Use official Postgres image that matches production database
FROM postgres:11.9

# Add metadata to the image
LABEL dev.waynelambert.author="Wayne Lambert <contact@waynelambert.dev>" \
    dev.waynelambert.version="2020.09" \
    dev.waynelambert.description="Docker image for postgres test database service"