# Use official Postgres image that matches production database
FROM postgres:14.6

# Add metadata to the image
LABEL dev.waynelambert.author="Wayne Lambert <wayne.a.lambert@gmail.com>" \
    dev.waynelambert.version="2022.12" \
    dev.waynelambert.description="Docker image for postgres test database service"
