from django.db import models

import pytest

from mixer.backend.django import mixer

from apps.countdown_letters.models import LettersGame


pytestmark = pytest.mark.django_db(reset_sequences=True)


class TestLettersGame:
    """
    Tests setup and config for the `LettersGame` model.

    The `letters_game` fixture represents a randomly generated instance
    of the attributes within the `LettersGame` class. This has been
    generated by the `mixer` package.
    """
    def test_single_letters_game_saves(self, letters_game):
        assert letters_game.pk == 1, 'Should create a `Letters letters_game` instance'

    def test_multi_letters_game_saves(self):
        games = mixer.cycle(10).blend(LettersGame)
        assert games[9].pk == 10, '10th instance should have a PK of 10'
        assert LettersGame.objects.count() == 10, 'Should have 10 objects in the database'

    def test_can_delete_letters_game(self):
        games = mixer.cycle(10).blend(LettersGame)
        games[4].delete()
        assert LettersGame.objects.count() == 9, 'Should have 9 objects remaining in the database'

    def test_letters_chosen_is_charfield(self, letters_game):
        field = letters_game._meta.get_field("letters_chosen")
        assert isinstance(field, models.CharField), 'Should be a char field'

    def test_players_word_is_charfield(self, letters_game):
        field = letters_game._meta.get_field("players_word")
        assert isinstance(field, models.CharField), 'Should be a char field'

    def test_comp_word_is_charfield(self, letters_game):
        field = letters_game._meta.get_field("comp_word")
        assert isinstance(field, models.CharField), 'Should be a char field'

    def test_eligible_answer_is_charfield(self, letters_game):
        field = letters_game._meta.get_field("eligible_answer")
        assert isinstance(field, models.BooleanField), 'Should be a boolean field'

    def test_winning_word_is_charfield(self, letters_game):
        field = letters_game._meta.get_field("winning_word")
        assert isinstance(field, models.CharField), 'Should be a char field'

    def test_player_word_len_is_integerfield(self, letters_game):
        field = letters_game._meta.get_field("player_word_len")
        assert isinstance(field, models.IntegerField), 'Should be an integer field'

    def test_comp_word_len_is_integerfield(self, letters_game):
        field = letters_game._meta.get_field("comp_word_len")
        assert isinstance(field, models.IntegerField), 'Should be an integer field'

    def test_player_score_is_integerfield(self, letters_game):
        field = letters_game._meta.get_field("player_score")
        assert isinstance(field, models.IntegerField), 'Should be an integer field'

    def test_comp_score_is_integerfield(self, letters_game):
        field = letters_game._meta.get_field("comp_score")
        assert isinstance(field, models.IntegerField), 'Should be an integer field'

    def test_definition_is_textfield(self, letters_game):
        field = letters_game._meta.get_field("definition")
        assert isinstance(field, models.TextField), 'Should be a text field'

    def test_word_class_is_charfield(self, letters_game):
        field = letters_game._meta.get_field("word_class")
        assert isinstance(field, models.CharField), 'Should be a char field'

    def test_result_is_charfield(self, letters_game):
        field = letters_game._meta.get_field("result")
        assert isinstance(field, models.CharField), 'Should be a char field'

    def test_entry_date_is_datefield(self, letters_game):
        field = letters_game._meta.get_field("entry_date")
        assert isinstance(field, models.DateField), 'Should be a date field'

    def test_entry_year(self, letters_game):
        assert letters_game.entry_year == letters_game.entry_date.year, \
            "Year should be the same as the entry date's year property"
