services:
  pg_test:
    image: ${COMPOSE_PROJECT_NAME}_pg_test_dev
    build:
      context: ./infra/dev/postgres/test
    container_name: ${COMPOSE_PROJECT_NAME}_pg_test_dev
    env_file:
      - .env
    tmpfs:
      - /var/lib/postgresql/data

  postgres:
    image: ${COMPOSE_PROJECT_NAME}_postgres_dev
    build:
      context: ./infra/dev/postgres
    container_name: ${COMPOSE_PROJECT_NAME}_postgres_dev
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - type: volume
        source: postgres_volume
        target: /var/lib/postgresql
    networks:
      - backend

  web:
    image: ${COMPOSE_PROJECT_NAME}_web_dev
    container_name: ${COMPOSE_PROJECT_NAME}_web_dev
    build:
      dockerfile: ./infra/dev/web/Dockerfile
      context: .
    command: >
      sh -c "python -Xfrozen_modules=off manage.py runserver 0.0.0.0:${WEB_PORT} --nostatic"
    restart: always
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
      - "${DEBUG_PORT}:${DEBUG_PORT}"
    env_file:
      - .env
    volumes:
      - .:/code
    depends_on:
      - postgres
    tty: true
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_volume:
