# Application Constants
@appResultsPageURLDev = http://localhost:8001/countdown-letters/results
@appResultsPageURLProd = https://waynelambert.dev/countdown-letters/results

# Choose either `lemmas` or `entries`
@endpointType = lemmas

# Game Variables
@lettersChosen = TUTRAESJB
@playersWord = TRUST


### Oxford Online Dictionary API
GET {{$dotenv OD_API_BASE_URL}}{{endpointType}}/en-gb/{{playersWord}} HTTP/1.1
app_id: {{$dotenv OD_APPLICATION_ID}}
app_key: {{$dotenv OD_APPLICATION_KEY_1}}


### Dev Server: Countdown Letters App Results Page
GET {{appResultsPageURLDev}}/?letters_chosen={lettersChosen}&players_word={{playersWord}} HTTP/1.1


### Prod Server: Countdown Letters App Results Page
GET {{appResultsPageURLProd}}/?letters_chosen={{lettersChosen}}&players_word={{playersWord}} HTTP/1.1
