# Generated by Django 3.1.1 on 2020-09-30 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_auto_20200922_2116"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="publish_date",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="updated_date",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
