# Generated by Django 3.1.1 on 2020-09-30 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_auto_20200930_2049"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Draft"), (1, "Publish")], db_index=True, default=0
            ),
        ),
    ]
