# Generated by Django 3.0.6 on 2020-06-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200601_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='\n        The slug can be any words you like separated by dashes.\n        Prepositions and pronouns are unncessary from an SEO perspective.\n        ', max_length=60, unique=True),
        ),
    ]
