# Generated by Django 3.0.6 on 2020-06-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200601_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(help_text='Select more than one category by holding down Ctrl or Cmd key', related_name='posts', to='blog.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=60, unique=True),
        ),
    ]
