# Generated by Django 3.0.6 on 2020-06-05 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200603_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated_date', '-publish_date']},
        ),
    ]
