# Generated by Django 3.0.6 on 2020-06-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200605_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default-post.jpg', help_text='For bests results, use an image that is 1,200px wide x 600px high', max_length=200, upload_to='post_images'),
        ),
    ]
