# Generated by Django 3.0.7 on 2020-06-23 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200623_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='The length of the post must be between 40 and 60 characters', max_length=60, validators=[django.core.validators.MinLengthValidator(40)]),
        ),
    ]
