# Generated by Django 3.2.5 on 2021-07-27 12:32

import apps.users.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_otp.util


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20201001_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_email_address', models.EmailField(max_length=254)),
                ('challenge_token_generated', models.CharField(default=django_otp.util.random_hex, help_text='Hex-encoded secret token', max_length=40, validators=[apps.users.utils.token_validator])),
                ('challenge_generation_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('challenge_expiration_timestamp', models.DateTimeField(default=apps.users.utils.get_challenge_expiration_timestamp, null=True)),
                ('challenge_token_returned', models.CharField(help_text='Hex-encoded secret token', max_length=40)),
                ('challenge_completed', models.BooleanField(default=False)),
                ('challenge_completed_timestamp', models.DateTimeField(editable=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_email_devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
