# Generated by Django 6.0.4 on 2026-04-26 19:25

import django_otp.util
import encrypted_model_fields.fields
import users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_generate_email_token_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtoken',
            name='challenge_expiration_timestamp',
            field=models.DateTimeField(blank=True, default=users.utils.get_challenge_expiration_timestamp, null=True),
        ),
        migrations.AlterField(
            model_name='emailtoken',
            name='challenge_token',
            field=encrypted_model_fields.fields.EncryptedCharField(default=django_otp.util.random_hex, validators=[users.utils.token_validator]),
        ),
    ]
