# Generated by Django 3.2.5 on 2021-08-05 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_add_encryption_to_challenge_token_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtoken',
            old_name='challenge_token_generated',
            new_name='challenge_token',
        ),
    ]
