# Generated by Django 3.2.6 on 2021-08-10 13:40

import apps.users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_challenge_completed_timestamp_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtoken',
            name='challenge_completed_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailtoken',
            name='challenge_expiration_timestamp',
            field=models.DateTimeField(blank=True, default=apps.users.utils.get_challenge_expiration_timestamp, null=True),
        ),
    ]
