# Generated by Django 3.2.6 on 2021-08-11 09:35

import apps.users.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_timestamp_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtoken',
            name='token_expiration_timestamp',
            field=models.DateTimeField(blank=True, default=apps.users.utils.get_token_expiration_timestamp, null=True),
        ),
    ]
