# Generated by Django 3.2.6 on 2021-08-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_add_token_expiration_timestamp_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtoken',
            name='token_expiration_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
