### The code gets the http response from the request the blog's API endpoint
### using the superuser login
GET http://localhost:8000/api/blog/
Authorization: Basic waynelambert testing321

### The code gets the http response from the request the blog's API endpoint
### using a standard user login
GET http://localhost:8000/api/blog/
Authorization: Basic bobbyrobson italia90

### Check request and response for a Google search
GET https://www.google.com/search?q=best+vs+code+extensions
