HTTP/1.1 403 Forbidden
Date: Sat, 13 Apr 2019 12:59:01 GMT
Server: WSGIServer/0.2 CPython/3.7.1
Content-Type: application/json
Vary: Accept, Cookie, Origin
Allow: GET, POST, HEAD, OPTIONS
X-Frame-Options: SAMEORIGIN
Content-Length: 39

{"detail":"Invalid username/password."}