# Use official Redis image as the base image
FROM redis:5.0.5-alpine

# Add metadata to the image
LABEL uk.co.waynelambert.author="Wayne Lambert <contact@waynelambert.co.uk>" \
    uk.co.waynelambert.version="2019.07" \
    uk.co.waynelambert.description="Docker image for redis service"