# Use official Redis image as the base image
FROM redis:5.0.5-alpine

# Add metadata to the image
LABEL dev.waynelambert.author="Wayne Lambert <contact@waynelambert.dev>" \
    dev.waynelambert.version="2019.07" \
    dev.waynelambert.description="Docker image for redis service"