# Pull Postgres v18.3 from Docker Hub
FROM postgres@sha256:a9abf4275f9e99bff8e6aed712b3b7dfec9cac1341bba01c1ffdfce9ff9fc34a

# Add metadata to image
LABEL dev.waynelambert.author="Wayne Lambert <wayne.a.lambert@gmail.com>" \
      dev.waynelambert.version="2026.04" \
      dev.waynelambert.description="Docker image for `postgres` service in dev."
