# Generated by Django 3.1.1 on 2020-09-16 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LettersGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letters_chosen', models.CharField(max_length=9)),
                ('players_word', models.CharField(max_length=9)),
                ('comp_word', models.CharField(max_length=9)),
                ('eligible_answer', models.BooleanField(default=False)),
                ('winning_word', models.CharField(max_length=9)),
                ('player_word_len', models.IntegerField(default=0)),
                ('comp_word_len', models.IntegerField(default=0)),
                ('player_score', models.IntegerField(default=0)),
                ('comp_score', models.IntegerField(default=0)),
                ('definition', models.TextField()),
                ('word_class', models.CharField(max_length=255)),
                ('result', models.CharField(max_length=255)),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-entry_date',),
            },
        ),
    ]
