# Generated by Django 3.0.8 on 2020-07-26 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countdown_letters', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='LettersGame',
        ),
    ]
